import './style/main.css';
import './style/fonts.css';
import './style/payment.css';
import './style/delivery.css';
import './style/pbi.css';
import 'bootstrap';
import './components/header';
import 'bootstrap/dist/css/bootstrap.min.css';
// import myImage from './public/les.jpg';
// $('body').css('background-color', 'red');
